### ISSUE TITLE
Avoid variadic functions

### ISSUE THREAD

**Issue by encukou** [capi-workgroup/api-evolution#12]
Avoid variadic functions. The feature isn't available in all languages that want to use the C-API.

(Per #4, these are fine as *alternatives* to functions with a fixed number of arguments.)

**Comment by pitrou** [comment]
This guideline is too strict IMHO. Rather, it should be:

For every variadic function in the C API, there should be a corresponding non-variadic function.

For example `PyObject *PyTuple_Pack(Py_ssize_t n, ...)` should also have a counterpart `PyObject *PyTuple_PackArray(Py_ssize_t n, PyObject**)`.

**Comment by encukou** [comment]
Yes, this guideline relies on the general exception mechanism in #4.
(IMO, if `PyTuple_Pack` was being added today, it should be named `PyTuple_VaPack` so that the variadic-ness is exposed in the name.)

**Comment by encukou** [comment]
Added to the draft in #53.
