### ISSUE TITLE
Process PEP establishing the C API Working Group

### ISSUE THREAD

**Issue by gvanrossum** [capi-workgroup/api-evolution#14]
Ultimately the goal of this repo (see the README) is to create a [process PEP](https://peps.python.org/pep-0001/#pep-types) co-authored by the C API Workgroup members. However we don't have a list of workgroup members, nor do we have a mandate establishing the workgroup.

Here is my proposal for how to establish the C API Workgroup. (I may edit this initial comment in place if later comments indicate I missed something.)

- [ ] Select workgroup members. I propose to start with @vstinner, @encukou, @zooba and myself (@gvanrossum). Others who want to participate (or disagree with this initial list) can add a comment here or contact me offline.
- [ ] The initial workgroup members draft a (meta) process PEP establishing the workgroup. I volunteer to do most of the writing.
- [ ] Circulate the PEP somewhere on Discourse.
- [ ] Submit the PEP to the Steering Council for approval.
- [ ] Wait for SC approval.

Once the C API Workgroup is officially established (as indicated by SC approval), the workgroup starts drafting another process PEP, containing guidelines for C API **evolution**. This PEP is intended as a live document, whose contents continue to be moderated by the workgroup members. (In practice, this PEP drafting process can start before the meta process PEP establishing the workgroup is accepted.)

"Radical" proposals (see the [api-revolution](https://github.com/capi-workgroup/api-revolution) repo) will need their own PEP. The C API Workgroup will advise the SC about those proposals (the [SC's position](https://github.com/python/steering-council/issues/201#issuecomment-1648848155) is apparently that in general C API issues are to be delegated to the C API Workgroup, so the workgroup has a strong voice in this, but I don't expect the workgroup to be able to accept C API PEPs independently of the SC).

CC: @encukou @vstinner @iritkatriel @colesbury @Yhg1s

**Comment by gvanrossum** [comment]
It's possible that we can crib some words from [PEP 729](https://peps.python.org/pep-0729/) which is currently being proposed (hasn't been sent to the SC AFAICT).

**Comment by encukou** [comment]
That sounds great!

**Comment by zooba** [comment]
I'm also interested in participating

**Comment by gvanrossum** [comment]
Here's a very early [PEP draft](https://github.com/gvanrossum/peps/blob/capi-pep/peps/pep-9999.rst). Note that I haven't filled out several sections yet -- I'm happy with Abstract, Epigraph, Motivation, and the first paragraph of Specification. The rest is either "Blah, Blah" or unchanged from Jelle's PEP 729.

**Comment by iritkatriel** [comment]
I'm interested in joining the group as a member, mostly to work on the incremental evolution stream.

**Comment by gvanrossum** [comment]
This is now a draft PR. Co-authors (@vstinner, @iritkatriel, @encukou, @zooba), please review: https://github.com/python/peps/pull/3476

**Comment by encukou** [comment]
PEP-731 was accepted. We are live.

The next step is tracked here: https://github.com/capi-workgroup/api-evolution/issues/44
